chore: create a setup action to help with CI/CD
nitrictech/setup-nitric pull request #1
Opened 2022-03-28 02:20 UTC by raksiv

Add support for installing nitric onto a git action, so that nitric commands can be utilized to deploy.

2022-03-28 02:21 UTC, raksiv commented
Will need to tag main with @v1 when merged.

2022-03-28 04:38 UTC, tjholm requested changes

2022-03-28 04:38 UTC, tjholm commented on src/main.ts
> +import * as core from "@actions/core";
Add copyright notice and licensing

2022-03-28 05:46 UTC, raksiv commented on src/main.ts
> +import * as core from "@actions/core";
Added

2022-03-30 00:28 UTC, davemooreuws approved these changes

2022-03-30 00:58 UTC, tjholm approved these changes

2022-03-30 01:05 UTC, merged